//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCP_Raza : EntidadBase
    {
        public GCP_Raza()
        {
            this.GCP_Mascota = new HashSet<GCP_Mascota>();
        }
    
        public int CodigoRaza { get; set; }
    
        public int CodigoEspecie { get; set; }
    
        public string NombreRaza { get; set; }
    
    
        public virtual GCP_Especie GCP_Especie { get; set; }
        public virtual ICollection<GCP_Mascota> GCP_Mascota { get; set; }
        public override string NombreEntidad { get { return "GCP_Raza"; } }
    }
    
}
