//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCP_Mascota : EntidadBase
    {
        public GCP_Mascota()
        {
            this.GCR_SolicitudRef = new HashSet<GCR_SolicitudRef>();
        }
    
        public int IdMascota { get; set; }
    
        public string CodigoMascota { get; set; }
    
        public string NombreMascota { get; set; }
    
        public string Genero { get; set; }
    
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    
        public Nullable<int> IdCliente { get; set; }
    
        public Nullable<int> idTamaño { get; set; }
    
        public Nullable<int> CodigoRaza { get; set; }
    
        public string Foto { get; set; }
    
        public Nullable<decimal> Peso { get; set; }
    
    
        public virtual GCP_Raza GCP_Raza { get; set; }
        public virtual ICollection<GCR_SolicitudRef> GCR_SolicitudRef { get; set; }
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public override string NombreEntidad { get { return "GCP_Mascota"; } }
    }
    
}
