//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCP_PersonaJuridica : EntidadBase
    {
        public GCP_PersonaJuridica()
        {
            this.GCR_RepresentanteClinica = new HashSet<GCR_RepresentanteClinica>();
        }
    
        public int IdCliente { get; set; }
    
        public string RUC { get; set; }
    
        public string RazonSocial { get; set; }
    
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual ICollection<GCR_RepresentanteClinica> GCR_RepresentanteClinica { get; set; }
        public override string NombreEntidad { get { return "GCP_PersonaJuridica"; } }
    }
    
}
