//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_Convenio : EntidadBase
    {
        public GCR_Convenio()
        {
            this.GCR_ConvenioServicio = new HashSet<GCR_ConvenioServicio>();
            this.GCR_SolicitudRef = new HashSet<GCR_SolicitudRef>();
            this.GCR_ConvenioDescuento = new HashSet<GCR_ConvenioDescuento>();
        }
    
        public int NroConvenio { get; set; }
    
        public Nullable<int> IdCliente { get; set; }
    
        public Nullable<int> NroSolicitud { get; set; }
    
        public Nullable<System.DateTime> FechaConvenio { get; set; }
    
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public Nullable<decimal> ImporteConvenio { get; set; }
    
        public string Observacion { get; set; }
    
        public string Estado { get; set; }
    
    
        public virtual GCR_Solicitud_Convenio GCR_Solicitud_Convenio { get; set; }
        public virtual ICollection<GCR_ConvenioServicio> GCR_ConvenioServicio { get; set; }
        public virtual ICollection<GCR_SolicitudRef> GCR_SolicitudRef { get; set; }
        public virtual ICollection<GCR_ConvenioDescuento> GCR_ConvenioDescuento { get; set; }
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public override string NombreEntidad { get { return "GCR_Convenio"; } }
    }
    
}
