//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_ConvenioDescuento : EntidadBase
    {
        public int NroConvenio { get; set; }
    
        public int Item { get; set; }
    
        public string Descripcion { get; set; }
    
        public Nullable<int> Minimo { get; set; }
    
        public Nullable<int> Maximo { get; set; }
    
        public Nullable<decimal> FactorDcto { get; set; }
    
    
        public virtual GCR_Convenio GCR_Convenio { get; set; }
        public override string NombreEntidad { get { return "GCR_ConvenioDescuento"; } }
    }
    
}
