//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_Solicitud_Convenio : EntidadBase
    {
        public GCR_Solicitud_Convenio()
        {
            this.GCR_Convenio = new HashSet<GCR_Convenio>();
            this.GCR_DocumentoRechazo = new HashSet<GCR_DocumentoRechazo>();
        }
    
        public int NroSolicitud { get; set; }
    
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
    
        public string Estado { get; set; }
    
        public string NroRUC { get; set; }
    
        public string Direccion { get; set; }
    
        public string RazonSocial { get; set; }
    
        public string Referencia { get; set; }
    
        public string Telefono { get; set; }
    
        public string Web { get; set; }
    
        public string TpoDocRep { get; set; }
    
        public string NroDocRep { get; set; }
    
        public string NombreRep { get; set; }
    
        public string TelefonoRep { get; set; }
    
        public string CorreoRep { get; set; }
    
        public string Nrogarantia { get; set; }
    
        public Nullable<System.DateTime> FechaVencimientoG { get; set; }
    
        public Nullable<int> IdBanco { get; set; }
    
        public Nullable<int> IdMoneda { get; set; }
    
        public Nullable<decimal> ImporteGarantia { get; set; }
    
        public string DocReciboTitulo { get; set; }
    
        public byte[] DocReciboObjeto { get; set; }
    
        public string DocColegiaturaTitulo { get; set; }
    
        public byte[] DocColegiaturaObjeto { get; set; }
    
        public string DocSunatTitulo { get; set; }
    
        public byte[] DocSunatObjeto { get; set; }
    
        public string DocLicenciaTitulo { get; set; }
    
        public byte[] DocLicenciaObjeto { get; set; }
    
        public string DocCentralTitulo { get; set; }
    
        public byte[] DocCentralObjeto { get; set; }
    
    
        public virtual ICollection<GCR_Convenio> GCR_Convenio { get; set; }
        public virtual ICollection<GCR_DocumentoRechazo> GCR_DocumentoRechazo { get; set; }
        public virtual GG_Banco GG_Banco { get; set; }
        public virtual GG_Moneda GG_Moneda { get; set; }
        public override string NombreEntidad { get { return "GCR_Solicitud_Convenio"; } }
    }
    
}
