//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_ContraReferencia : EntidadBase
    {
        public int NroContraReferencia { get; set; }
    
        public Nullable<int> NroSolicitudRef { get; set; }
    
        public Nullable<System.DateTime> FechaCierre { get; set; }
    
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public string Observaciones { get; set; }
    
        public Nullable<int> IdVeterinario { get; set; }
    
        public string Resultados { get; set; }
    
    
        public virtual GCR_SolicitudRef GCR_SolicitudRef { get; set; }
        public virtual GCR_Veterinario GCR_Veterinario { get; set; }
        public override string NombreEntidad { get { return "GCR_ContraReferencia"; } }
    }
    
}
