//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_Veterinario : EntidadBase
    {
        public GCR_Veterinario()
        {
            this.GCR_ContraReferencia = new HashSet<GCR_ContraReferencia>();
        }
    
        public int IdVeterinario { get; set; }
    
        public string NomVeterinario { get; set; }
    
        public string Estado { get; set; }
    
    
        public virtual ICollection<GCR_ContraReferencia> GCR_ContraReferencia { get; set; }
        public override string NombreEntidad { get { return "GCR_Veterinario"; } }
    }
    
}
