//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_RepresentanteClinica : EntidadBase
    {
        public string TpoDocRep { get; set; }
    
        public string NroDocRep { get; set; }
    
        public Nullable<int> IdCliente { get; set; }
    
        public string NombresRep { get; set; }
    
        public string TelefonoRep { get; set; }
    
        public string CorreoRep { get; set; }
    
    
        public virtual GCP_PersonaJuridica GCP_PersonaJuridica { get; set; }
        public override string NombreEntidad { get { return "GCR_RepresentanteClinica"; } }
    }
    
}
