//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_Liquidaciones : EntidadBase
    {
        public GCR_Liquidaciones()
        {
            this.GCR_Atenciones = new HashSet<GCR_Atenciones>();
        }
    
        public int NroLiquidacion { get; set; }
    
        public string Anio { get; set; }
    
        public string Mes { get; set; }
    
        public Nullable<int> IdCliente { get; set; }
    
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
    
        public Nullable<decimal> ValorBruto { get; set; }
    
        public Nullable<decimal> ValorDctoComercial { get; set; }
    
        public Nullable<decimal> ValorNeto { get; set; }
    
        public Nullable<decimal> ValorImpuesto { get; set; }
    
        public Nullable<decimal> ValorTotal { get; set; }
    
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual ICollection<GCR_Atenciones> GCR_Atenciones { get; set; }
        public override string NombreEntidad { get { return "GCR_Liquidaciones"; } }
    }
    
}
