//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_ConvenioServicio : EntidadBase
    {
        public GCR_ConvenioServicio()
        {
            this.GCR_SolicitudRef_Servicio = new HashSet<GCR_SolicitudRef_Servicio>();
        }
    
        public int IdServicio { get; set; }
    
        public int NroConvenio { get; set; }
    
        public Nullable<decimal> TarifaBase { get; set; }
    
        public Nullable<decimal> FactorDcto { get; set; }
    
        public Nullable<decimal> TarifaReal { get; set; }
    
        public string Estado { get; set; }
    
    
        public virtual GCR_Convenio GCR_Convenio { get; set; }
        public virtual GG_Servicio GG_Servicio { get; set; }
        public virtual ICollection<GCR_SolicitudRef_Servicio> GCR_SolicitudRef_Servicio { get; set; }
        public override string NombreEntidad { get { return "GCR_ConvenioServicio"; } }
    }
    
}
