//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GCR_Atenciones : EntidadBase
    {
        public int IdAtencion { get; set; }
    
        public Nullable<int> NroSolicitudRef { get; set; }
    
        public Nullable<int> IdServicio { get; set; }
    
        public Nullable<int> NroConvenio { get; set; }
    
        public Nullable<int> Cantidad { get; set; }
    
        public Nullable<decimal> TarifaBase { get; set; }
    
        public Nullable<decimal> ValorBruto { get; set; }
    
        public Nullable<decimal> Descuento { get; set; }
    
        public Nullable<decimal> ValorNeto { get; set; }
    
        public Nullable<int> NroLiquidacion { get; set; }
    
        public string Resultado { get; set; }
    
        public string ResultadoTitulo { get; set; }
    
        public byte[] ResultadoObjeto { get; set; }
    
        public string Estado { get; set; }
    
        public Nullable<System.DateTime> FechaAtencion { get; set; }
    
    
        public virtual GCR_Liquidaciones GCR_Liquidaciones { get; set; }
        public virtual GCR_SolicitudRef_Servicio GCR_SolicitudRef_Servicio { get; set; }
        public override string NombreEntidad { get { return "GCR_Atenciones"; } }
    }
    
}
