//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class GG_Moneda : EntidadBase
    {
        public GG_Moneda()
        {
            this.GCR_Solicitud_Convenio = new HashSet<GCR_Solicitud_Convenio>();
        }
    
        public int IdMoneda { get; set; }
    
        public string DesMoneda { get; set; }
    
    
        public virtual ICollection<GCR_Solicitud_Convenio> GCR_Solicitud_Convenio { get; set; }
        public override string NombreEntidad { get { return "GG_Moneda"; } }
    }
    
}
