//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class Moneda : EntidadBase
    {
        public Moneda()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int IdMoneda { get; set; }
    
        public string Descripcion { get; set; }
    
    
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public override string NombreEntidad { get { return "Moneda"; } }
    }
    
}
