//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Dominio.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    using PetCenter.Referencias.Dominio.Logica.Base;
    
    public partial class Solicitud : EntidadBase
    {
        public int IdSolicitud { get; set; }
    
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
    
        public string NroRuc { get; set; }
    
        public string Direccion { get; set; }
    
        public string Referencia { get; set; }
    
        public string RazonSocial { get; set; }
    
        public string Telefono { get; set; }
    
        public string Web { get; set; }
    
        public int IdTipoDocumento { get; set; }
    
        public string NroDocumento { get; set; }
    
        public string NombresCompletos { get; set; }
    
        public string Email { get; set; }
    
        public string TelefonoRep { get; set; }
    
        public int IdBanco { get; set; }
    
        public int IdMoneda { get; set; }
    
        public Nullable<decimal> Monto { get; set; }
    
        public string NroReferencia { get; set; }
    
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
    
        public virtual Banco Banco { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public override string NombreEntidad { get { return "Solicitud"; } }
    }
    
}
