//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Infraestructura.Data.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using PetCenter.Referencias.Dominio.Logica.Entidades;
    using System.Collections.Generic;
     
    public partial class BD_ReferenciaEntities : DbContext
    {
        public BD_ReferenciaEntities()
            : base("name=BD_ReferenciaEntities")
        {
            Configuration.ProxyCreationEnabled = false;
            Configuration.LazyLoadingEnabled = false;
            Configuration.AutoDetectChangesEnabled = false;
            Configuration.ValidateOnSaveEnabled = false;
            Database.SetInitializer<BD_ReferenciaEntities>(null);
        }
    
        public void EnableDetectChange()
        {
            Configuration.AutoDetectChangesEnabled = true;
        }
    
        public void DisableDetectChange()
        {
            Configuration.AutoDetectChangesEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Banco> Banco { get; set; }
        public DbSet<Moneda> Moneda { get; set; }
        public DbSet<Solicitud> Solicitud { get; set; }
        public DbSet<TipoDocumento> TipoDocumento { get; set; }
    
        public IEnumerable<TEntidad> ExecuteStoreQuery<TEntidad>(string sqlQuery, params object[] parameters)
        {
            var context = ((IObjectContextAdapter)this).ObjectContext;
            return context.ExecuteStoreQuery<TEntidad>(sqlQuery, parameters);
        }
    
        public int ExecuteStoreCommand(string sqlCommand, params object[] parameters)
        {
            var context = ((IObjectContextAdapter)this).ObjectContext;
            return context.ExecuteStoreCommand(sqlCommand, parameters);
        }
    
    }
}
