//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Infraestructura.Data.UnidadDeTrabajo
{
    using PetCenter.Referencias.Dominio.Logica.Entidades;
    using PetCenter.Referencias.Infraestructura.Data.Base;
    using System.Data.Entity;
    
    public interface IModeloReferenciaUnidadDeTrabajo : IConsultableUnidadDeTrabajo
    {
        DbSet<Banco> Banco { get; set; }
        DbSet<Moneda> Moneda { get; set; }
        DbSet<Solicitud> Solicitud { get; set; }
        DbSet<TipoDocumento> TipoDocumento { get; set; }
    }
}
