//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Presentacion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentType() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetCenter.Referencias.Presentacion.Web.Resources.ContentType", typeof(ContentType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/bmp.
        /// </summary>
        public static string CT_Bmp {
            get {
                return ResourceManager.GetString("CT_Bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a text/csv.
        /// </summary>
        public static string CT_Csv {
            get {
                return ResourceManager.GetString("CT_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/octet-stream.
        /// </summary>
        public static string CT_Desconocido {
            get {
                return ResourceManager.GetString("CT_Desconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/excel.
        /// </summary>
        public static string CT_Excel {
            get {
                return ResourceManager.GetString("CT_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        public static string CT_ExcelX {
            get {
                return ResourceManager.GetString("CT_ExcelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/gif.
        /// </summary>
        public static string CT_Gif {
            get {
                return ResourceManager.GetString("CT_Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/x-icon.
        /// </summary>
        public static string CT_Icon {
            get {
                return ResourceManager.GetString("CT_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/jpeg.
        /// </summary>
        public static string CT_Jpg {
            get {
                return ResourceManager.GetString("CT_Jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/pdf.
        /// </summary>
        public static string CT_Pdf {
            get {
                return ResourceManager.GetString("CT_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/png.
        /// </summary>
        public static string CT_Png {
            get {
                return ResourceManager.GetString("CT_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pplication/x-rar-compressed.
        /// </summary>
        public static string CT_Rar {
            get {
                return ResourceManager.GetString("CT_Rar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a text/plain.
        /// </summary>
        public static string CT_Text {
            get {
                return ResourceManager.GetString("CT_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a image/tiff.
        /// </summary>
        public static string CT_Tif {
            get {
                return ResourceManager.GetString("CT_Tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/msword.
        /// </summary>
        public static string CT_Word {
            get {
                return ResourceManager.GetString("CT_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        public static string CT_WordX {
            get {
                return ResourceManager.GetString("CT_WordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a application/zip.
        /// </summary>
        public static string CT_Zip {
            get {
                return ResourceManager.GetString("CT_Zip", resourceCulture);
            }
        }
    }
}
