//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Referencias.Presentacion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Formatos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formatos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetCenter.Referencias.Presentacion.Web.Resources.Formatos", typeof(Formatos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}{1}.
        /// </summary>
        public static string CodigoPago {
            get {
                return ResourceManager.GetString("CodigoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ##.00.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        public static string FechaCorta {
            get {
                return ResourceManager.GetString("FechaCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm:ss.
        /// </summary>
        public static string FechaHora {
            get {
                return ResourceManager.GetString("FechaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm.
        /// </summary>
        public static string FechaHoraCorta {
            get {
                return ResourceManager.GetString("FechaHoraCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yyyy_MM_dd.
        /// </summary>
        public static string FechaLog {
            get {
                return ResourceManager.GetString("FechaLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0{0}000{1}.
        /// </summary>
        public static string PreCodigoPago {
            get {
                return ResourceManager.GetString("PreCodigoPago", resourceCulture);
            }
        }
    }
}
